# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "People"
  weight = 15
  
[[main]]
  parent = "People"
  name = "Lab members"
  url = "people/"
  weight = 20
  
[[main]]
  parent = "People"
  name = " Alumni"
  url = "alumni/"
  weight = 30

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 40

[[main]]
  name = "Teaching"
  url = "teaching/"
  weight = 50

[[main]]
  name = "Resources"
  url = "resource/"
  weight = 60

[[main]]
  name = "News"
  url = "news/"
  weight = 70
  
[[main]]
  name = "Lablog"
  url = "lablog/"
  weight = 80

#[[main]]
#  name = "Posts"
#  url = "post/"
#  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
